### ISSUE TITLE
Cant use the program

### ISSUE THREAD

**Issue by BluDvD** [SergejBre/SynchroTime#2]
Hi

I am trying to use your program but when i compile it, outputs a error. But if i change the time_t to time_v, it compiles normally. ![2](https://user-images.githubusercontent.com/63650234/151591419-c62b3962-0de2-49d2-ae07-e53ee829a23f.PNG)

When it compiles normally, i cant sync the RTC module to the program.![3](https://user-images.githubusercontent.com/63650234/151591435-f8b30e9c-06a9-4241-a0c8-c826bc236466.PNG)

The connections are:

Vcc = 3.3v(because if i use 5v, the power led dont come on...)
GND = GND
SDA = A4
SCL = A5
SQW = D2

**Comment by SergejBre** [comment]
Hi,

sketch synchro_RTC.ino is adapted for Visual C++ compiler use. It should compile without errors.

Check the synchronization of the module with the application again. In case of doubt about data exchange, check the arduino with any COM port monitor. After a successful start of the firmware, debug information and the temperature of the crystal should appear:

`Boot.. Ok, T[°С]=20.5`
