### ISSUE TITLE
Компиляция под esp8266

### ISSUE THREAD

**Issue by didos06** [SergejBre/SynchroTime#3]
Можно ли подправить скетч под esp? При выборе данных плат возникает ошибка:
exit status 1
conflicting declaration 'typedef struct time_s time_t' , указывая на строку 50.
Использую скетч synchro_RTC_alt.
При выборе arduino nano всё успешно компилируется, но у меня её нет в наличии.
Та же ошибка с esp32.
Понимаю, проект писался не под эти мк, но всё-же.
Проект был бы более универсальным.

**Comment by JS80PICuser** [comment]
Same issue with time_t on ESP32 WROOVER board, impossible to compile sketch, it's a shame this project seems very interesting, unfortunately I don't have enough experience for the moment to solve this conflict...  if someone could help us it would be nice ! 
sketch_sep01a:50:3: error: conflicting declaration 'typedef struct time_s time_t'
 } time_t;
   ^~~~~~  etc.

**Comment by SergejBre** [comment]
The synchro_RTC_alt sketch has been successfully edited according to the compiler standards for the ESP8266 module
